// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk8_gElLhOzjT9swldT0-zCCbftAgJNM8',
    appId: '1:19759420718:web:5cc9b7c88bfe2dce12d6bf',
    messagingSenderId: '19759420718',
    projectId: 'roma-note-app',
    authDomain: 'roma-note-app.firebaseapp.com',
    storageBucket: 'roma-note-app.firebasestorage.app',
    measurementId: 'G-YLPNC1VVM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbOD7Tt3PpI8avd4uTHzKUNVW_Wvr7GkU',
    appId: '1:19759420718:android:d202fc375d11fb8b12d6bf',
    messagingSenderId: '19759420718',
    projectId: 'roma-note-app',
    storageBucket: 'roma-note-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmGOSG2AEGOviLfUMtSejEXgz5EFBloiQ',
    appId: '1:19759420718:ios:af77f97313c6ac2012d6bf',
    messagingSenderId: '19759420718',
    projectId: 'roma-note-app',
    storageBucket: 'roma-note-app.firebasestorage.app',
    iosBundleId: 'com.example.notesListExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmGOSG2AEGOviLfUMtSejEXgz5EFBloiQ',
    appId: '1:19759420718:ios:af77f97313c6ac2012d6bf',
    messagingSenderId: '19759420718',
    projectId: 'roma-note-app',
    storageBucket: 'roma-note-app.firebasestorage.app',
    iosBundleId: 'com.example.notesListExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk8_gElLhOzjT9swldT0-zCCbftAgJNM8',
    appId: '1:19759420718:web:301a2227240f2cff12d6bf',
    messagingSenderId: '19759420718',
    projectId: 'roma-note-app',
    authDomain: 'roma-note-app.firebaseapp.com',
    storageBucket: 'roma-note-app.firebasestorage.app',
    measurementId: 'G-RHYY9847JE',
  );
}
